### CARGAR Y LIMPIAR DATOS USANDO ARCHIVOS .csv

In [11]:
#Cargar todos los archivos con los que vamos a trabajar
"""Primero converti todos los archivos a .csv desde Excel"""

import pandas as pd

category = pd.read_csv("DIM_CATEGORY.csv")
product = pd.read_csv("DIM_PRODUCT.csv")
segment = pd.read_csv("DIM_SEGMENT.csv")
calendar = pd.read_csv("DIM_CALENDAR.csv")
sales = pd.read_csv("FACT_SALES.csv")

In [26]:
#REVISAR LAS TABLAS
category

   ID_CATEGORY                        CATEGORY
0            1  FABRIC TREATMENT and SANIT\r\n
1            2                       AIR CARE
2            3                    LAVAVAJILLAS
3            4                MEGA SUPERFICIES
4            5             LAVATORY CARE & BRC

In [21]:
product

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
...,...,...,...,...,...,...,...,...,...
500,RECKITT,VANISH,7501058789778BP1,VANISH EXT HIGIENE REM MANCHAS GAL 4LT + VANIS...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,ROSA
501,INDS. ALEN,CLORALEX,7501025412142,CLORALEX AROMAS BLANQUEADOR C/AROMA LAVANDA GA...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
502,INDS. ALEN,CLORALEX,NaN,CLORALEX EL RENDIDOR BOT PLAST 2LT,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
503,CLOROX,CLOROX,NaN,CLOROX MASCOTAS BLANQUEADOR+DETERGENTE GALON 10L,1,LIQUIDO,CLORO,CLORO,MASCOTAS
504,CLOROX,CLOROX,7502240948188BP1,CLOROX BLANQ930M+MMBLANQINOD709M+MMFIBRAULTRA1...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

In [22]:
segment

,CATEGORY,ATTR1,ATTR2,ATTR3,FORMAT,SEGMENT
0,1,CLORO,CLORO,BAMBINO,LIQUIDO,BLEACH
1,1,CLORO,CLORO,GERMICIDA,LIQUIDO,BLEACH
2,1,CLORO,CLORO,MASCOTAS,LIQUIDO,BLEACH
3,1,CLORO,CLORO,MULTIUSOS,GEL,BLEACH
4,1,CLORO,CLORO,MULTIUSOS,LIQUIDO,BLEACH
5,1,CLORO,CLORO,NO DEFINIDO,LIQUIDO,BLEACH
6,1,CLORO,CLORO,NO DEFINIDO,POLVO,BLEACH
7,1,CLORO,CLORO,OTR. TIPOS,LIQUIDO,BLEACH
8,1,CLORO,CLORO,OTR. TIPOS,POLVO,BLEACH
9,1,CLORO,CLORO,ROPA BEBE,LIQUIDO,BLEACH
10,1,CLORO,CLORO,NaN,LIQUIDO,BLEACH
11,1,CLORO,MASCOTAS,MASCOTAS,LIQUIDO,BLEACH
12,1,CLORO,MULTIUSOS,MULTIUSOS,GEL,BLEACH
13,1,CLORO,NO DEFINIDO,NO DEFINIDO,LIQUIDO,BLEACH
14,1,PRELAVADOR,FABRIC TREATMENT,BLANCO,GEL,LIQUID & GEL
15,1,PRELAVADOR,FABRIC TREATMENT,BLANCO,POLVO,POWDER
16,1,PRELAVADOR,FABRIC TREATMENT,BLANCO,TOALLAS,OTHERS
17,1,PRELAVADOR,FABRIC TREATMENT,OTR. TIPOS,LIQUIDO,PRETREAT
18,1,PRELAVADOR,FABRIC TREATMENT,PRE LAVADOR,LIQUIDO,PRETREAT
19,1,PRELAVADOR,FABRIC TREATMENT,PRE LAVADOR,POLVO,POWDER
20,1,PRELAVADOR,FABRIC TREATMENT,QUITAMANCHAS,LIQUIDO,PRETREAT
21,1,PRELAVADOR,FABRIC TREATMENT,ROPA COLOR,LIQUIDO,PRETREAT
22,1,PRELAVADOR,FABRIC TREATMENT,ROSA,GEL,LIQUID & GEL
23,1,PRELAVADOR,FABRIC TREATMENT,ROSA,LIQUIDO,PRETREAT
24,1,PRELAVADOR,FABRIC TREATMENT,ROSA,POLVO,POWDER
25,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,BARRA,BAR
26,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,GEL,LIQUID & GEL
27,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,LIQUIDO,LIQUID & GEL
28,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,POLVO,POWDER
29,1,SAFE BLEACH,FABRIC TREATMENT,COLOR PODER VINAGRE,GEL,LIQUID & GEL
30,1,SAFE BLEACH,FABRIC TREATMENT,COLOR PODER VINAGRE,LIQUIDO,LIQUID & GEL
31,1,SAFE BLEACH,FABRIC TREATMENT,OTR. TIPOS,BARRA,BAR
32,1,SAFE BLEACH,FABRIC TREATMENT,OTR. TIPOS,GEL,LIQUID & GEL
33,1,SAFE BLEACH,FABRIC TREATMENT,OTR. TIPOS,LIQUIDO,LIQUID & GEL
34,1,SAFE BLEACH,FABRIC TREATMENT,OTR. TIPOS,POLVO,POWDER
35,1,SAFE BLEACH,FABRIC TREATMENT,PODER OXIGENO,GEL,LIQUID & GEL
36,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,BARRA,BAR
37,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,GEL,LIQUID & GEL
38,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,LIQUIDO,PRETREAT
39,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,POLVO,POWDER
40,1,SAFE BLEACH,FABRIC TREATMENT,QUITAMANCHAS,GEL,LIQUID & GEL
41,1,SAFE BLEACH,FABRIC TREATMENT,QUITAMANCHAS,LIQUIDO,LIQUID & GEL
42,1,SAFE BLEACH,FABRIC TREATMENT,QUITAMANCHAS,POLVO,POWDER
43,1,SAFE BLEACH,FABRIC TREATMENT,ROPA BLANCA,LIQUIDO,LIQUID & GEL
44,1,SAFE BLEACH,FABRIC TREATMENT,ROPA BLANCA,POLVO,POWDER
45,1,SAFE BLEACH,FABRIC TREATMENT,ROPA COLOR,LIQUIDO,LIQUID & GEL
46,1,SAFE BLEACH,FABRIC TREATMENT,ROPA COLOR,POLVO,POWDER
47,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,BARRA,BAR
48,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,GEL,LIQUID & GEL
49,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,LIQUIDO,LIQUID & GEL
50,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,POLVO,POWDER
51,1,SAFE BLEACH,PRE LAVADOR,PRE LAVADOR,GEL,PRETREAT
52,1,SANITIZANTE,SANITIZANTE,SANITIZANTE,LIQUIDO,SANITIZER

In [23]:
calendar

      WEEK  YEAR  MONTH  WEEK_NUMBER      DATE
0    01-21  2021      1            1  10/01/21
1    02-21  2021      1            2  17/01/21
2    03-21  2021      1            3  24/01/21
3    04-21  2021      1            4  31/01/21
4    05-21  2021      2            5  07/02/21
..     ...   ...    ...          ...       ...
151  48-23  2023     12           48  04/12/23
152  49-23  2023     12           49  11/12/23
153  50-23  2023     12           50  18/12/23
154  51-23  2023     12           51  25/12/23
155  52-23  2023      1           52  01/01/24

[156 rows x 5 columns]

In [27]:
sales

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5
...,...,...,...,...,...,...
121997,26-23,7501058792778BP1,1.192,150.829,4.000,TOTAL AUTOS SCANNING MEXICO
121998,26-23,7501058757630,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO
121999,26-23,7501058753441,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO
122000,26-23,7702626204208BP1,21.152,210.276,22.172,TOTAL AUTOS SCANNING MEXICO
122001,26-23,7501058784346,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO

In [25]:
#REVISAR NULOS Y DUPLICADOS
# Valores nulos
print("Valores nulos por tabla:")
print(category.isnull().sum())
print(product.isnull().sum())
print(segment.isnull().sum())
print(calendar.isnull().sum())
print(sales.isnull().sum())

Valores nulos por tabla:
ID_CATEGORY    0
CATEGORY       0
dtype: int64
MANUFACTURER        0
BRAND               0
ITEM                2
ITEM_DESCRIPTION    0
CATEGORY            0
FORMAT              0
ATTR1               6
ATTR2               0
ATTR3               6
dtype: int64
CATEGORY    0
ATTR1       0
ATTR2       0
ATTR3       1
FORMAT      0
SEGMENT     0
dtype: int64
WEEK           0
YEAR           0
MONTH          0
WEEK_NUMBER    0
DATE           0
dtype: int64
WEEK                           0
ITEM_CODE                      0
TOTAL_UNIT_SALES               0
TOTAL_VALUE_SALES              0
TOTAL_UNIT_AVG_WEEKLY_SALES    0
REGION                         0
dtype: int64

In [35]:
#Eliminar Duplicados
category = category.drop_duplicates()
product = product.drop_duplicates()
segment = segment.drop_duplicates()
calendar = calendar.drop_duplicates()
sales = sales.drop_duplicates()

In [36]:
# FACT_SALES + DIM_CALENDAR
sales_calendar = sales.merge(
    calendar,
    on="WEEK",
    how="left"
)

# DIM_PRODUCT + DIM_CATEGORY
# Asegurar que CATEGORY sea string en ambas tablas
product["CATEGORY"] = product["CATEGORY"].astype(str)
category["ID_CATEGORY"] = category["ID_CATEGORY"].astype(str)

prod_cat = product.merge(
    category,
    left_on="CATEGORY",     # columna en dim_product
    right_on="ID_CATEGORY", # columna en dim_category
    how="left"
)

# DIM_PRODUCT + DIM_SEGMENT
# (sin CATEGORY, solo ATTR1-3 y FORMAT)
prod_seg = product.merge(
    segment,
    on=["ATTR1", "ATTR2", "ATTR3", "FORMAT"],
    how="left"
)

# DIM_PRODUCT + DIM_CATEGORY + DIM_SEGMENT
prod_cat_seg = product.merge(
    category,
    left_on="CATEGORY",
    right_on="ID_CATEGORY",
    how="left"
).merge(
    segment,
    on=["ATTR1", "ATTR2", "ATTR3", "FORMAT"],
    how="left"
)

In [38]:
# Revisar Resultados
print("FACT_SALES + CALENDAR")
display(sales_calendar.head())

print("PRODUCTO + CATEGORÍA")
display(prod_cat.head())

print("PRODUCTO + SEGMENTO")
display(prod_seg.head())

print("PRODUCTO + CATEGORÍA + SEGMENTO")
display(prod_cat_seg.head())

FACT_SALES + CALENDAR

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,YEAR,MONTH,WEEK_NUMBER,DATE
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5,2022,8,34,28/08/22
1,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5,2022,8,34,28/08/22
2,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5,2022,8,34,28/08/22
3,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5,2022,8,34,28/08/22
4,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5,2022,8,34,28/08/22

PRODUCTO + CATEGORÍA

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY_x,FORMAT,ATTR1,ATTR2,ATTR3,ID_CATEGORY,CATEGORY_y
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1,1
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1,1
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1,1
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1,1
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1,1

PRODUCTO + SEGMENTO

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY_x,FORMAT,ATTR1,ATTR2,ATTR3,CATEGORY_y,SEGMENT
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1.0,BLEACH
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1.0,BLEACH
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1.0,BLEACH
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1.0,BLEACH
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1.0,BLEACH

PRODUCTO + CATEGORÍA + SEGMENTO

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY_x,FORMAT,ATTR1,ATTR2,ATTR3,ID_CATEGORY,CATEGORY_y,CATEGORY,SEGMENT
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1,1,1.0,BLEACH
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1,1,1.0,BLEACH
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1,1,1.0,BLEACH
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1,1,1.0,BLEACH
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1,1,1.0,BLEACH

In [ ]:
#Las tablas tienen algunos errores, no se pueden relacionar algunas columnas con otras porque no tienen una relación exacta
#Uni algunas donde si concordaba la información